export const forest: string[] = [
	`Anthologies`,
	`Avacyn Restored`,
	`Bloomburrow`,
	`Commander`,
	`Commander 2013`,
	`Commander 2015`,
	`Ajani vs. Nicol Bolas`,
	`Elspeth vs. Kiora`,
	`Phyrexia vs. the Coalition`,
	`Duskmourn: House of Horror`,
	`Edge of Eternities`,
	`Edition`,
	`Fifth Edition`,
	`Final Fantasy`,
	`Fourth Edition`,
	`Ice Age`,
	`Innistrad`,
	`Invasion`,
	`Khans of Tarkir`,
	`Beta`,
	`Lorwyn Eclipsed`,
	`Magic 2011`,
	`Magic 2012`,
	`Magic 2013`,
	`Magic 2014`,
	`Magic 2015`,
	`Mirage`,
	`Mirrodin Besieged`,
	`New Phyrexia`,
	`Portal`,
	`Portal Second Age`,
	`Ravnica: Clue Edition`,
	`Return to Ravnica`,
	`Revised`,
	`Rise of the Eldrazi`,
	`Scars of Mirrodin`,
	`Secrets of Strixhaven`,
	`Teenage Mutant Ninja Turtles`,
	`Tenth Edition`,
	`The Hobbit`,
	`Theros`,
	`Unstable`,
	`Urza's Saga`,
	`War of the Spark`,
	`Zendikar`,
];
