export const island: string[] = [
	`Avacyn Restored`,
	`Battle for Zendikar`,
	`Bloomburrow`,
	`Commander`,
	`Commander 2013`,
	`Commander 2014`,
	`Commander 2015`,
	`Elspeth vs. Kiora`,
	`Duskmourn: House of Horror`,
	`Edge of Eternities`,
	`Edition`,
	`Fifth Edition`,
	`Final Fantasy`,
	`Guilds of Ravnica`,
	`Ice Age`,
	`Innistrad`,
	`Innistrad Remastered`,
	`Kaladesh`,
	`Khans of Tarkir`,
	`Lorwyn`,
	`Lorwyn Eclipsed`,
	`Magic 2011`,
	`Magic 2012`,
	`Magic 2013`,
	`Magic 2014`,
	`Magic 2015`,
	`Marvel Super Heroes`,
	`Marvel's Spider-Man`,
	`Mirage`,
	`Mirrodin Besieged`,
	`Murders at Karlov Manor`,
	`Odyssey`,
	`Onslaught`,
	`Outlaws of Thunder Junction`,
	`Portal`,
	`Ravnica: City of Guilds`,
	`Ravnica: Clue Edition`,
	`Return to Ravnica`,
	`Revised`,
	`Scars of Mirrodin`,
	`Secrets of Strixhaven`,
	`Tempest`,
	`Tenth Edition`,
	`The Hobbit`,
	`Theros`,
	`Unstable`,
	`Urza's Saga`,
	`War of the Spark`,
	`Zendikar`,
];
