/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by scripts/tokens-generate.js

/* Build fallback font families */
/* Note: fallback tokens are optional, so they're read as a plain string map and a project without them gets an empty list */
const json: Record<string, string> = (themeJson as { fallback?: Record<string, string> }).fallback ?? {};
const keys = Object.keys(json).filter((key) => key.startsWith('src-'));
const data: FallbackType[] = [];

keys.forEach((fallback) => {
	const key = fallback.includes('header') ? 'header' : 'body';

	const config: FallbackType = {
		family: json[`name-${key}`],
		size: json[`size-${key}`],
		src: json[fallback],
	};

	data.push(config);
});

export const fallbacks = data;
