/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by scripts/tokens-generate.js

/* Build fallback font families */
/* Note: only src- keys are used in the loop, so the filter narrows the keys to those (their values are always strings) */
const json = themeJson.fallback;
const keys = (Object.keys(json) as (keyof FallbacksJsonType)[]).filter((key): key is Extract<keyof FallbacksJsonType, `src-${string}`> =>
	key.startsWith('src-'),
);
const data: FallbackType[] = [];

keys.forEach((fallback) => {
	const current = json[fallback];
	const key = fallback.includes('header') ? 'header' : 'body';

	const config: FallbackType = {
		family: json[`name-${key}` as const],
		size: json[`size-${key}` as const],
		src: current,
	};

	data.push(config);
});

export const fallbacks = data;
