/* Packages */
import { getFallbacks } from '@displaycoffee/tokens';

/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by tokens-generate (@displaycoffee/tokens)

export const fallbacks = getFallbacks(themeJson);
