/* Packages */
import { getFavicons } from '@displaycoffee/tokens';

/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by tokens-generate (@displaycoffee/tokens)

export const favicons = getFavicons(themeJson);
