/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by scripts/tokens-generate.js

/* Build favicons */
/* Note: favicon tokens are optional, so they're read as a plain map and a project without them gets an empty list */
const json: Record<string, string | boolean> = (themeJson as { favicon?: Record<string, string | boolean> }).favicon ?? {};
const keys = Object.keys(json).filter((key) => key.startsWith('src-'));
const data: FaviconType[] = [];

/* Not every favicon has head / manifest / purpose / sizes tokens, so these return a fallback when a token is missing */
const getBoolean = (name: string) => json[name] === true;
const getString = (name: string) => {
	const value = json[name];
	return typeof value === 'string' ? value : undefined;
};

keys.forEach((favicon) => {
	const current = getString(favicon) ?? '';
	const key = favicon.replace('src-', '');
	const size = getString(`size-${key}`) ?? '';

	// Set type attribute
	let type = 'image/png';
	if (current.includes('.svg')) {
		type = 'image/svg+xml';
	} else if (current.includes('.ico')) {
		type = 'image/x-icon';
	}

	const config: FaviconType = {
		isHead: getBoolean(`head-${key}`),
		isManifest: getBoolean(`manifest-${key}`),
		purpose: getString(`purpose-${key}`) ?? 'any',
		rel: current.includes('apple-touch-icon') ? 'apple-touch-icon' : 'icon',
		src: current,
		size: size,
		sizes: getString(`sizes-${key}`) ?? size,
		type: type,
	};

	data.push(config);
});

export const favicons = data;
