/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by scripts/tokens-generate.js

/* Build favicons */
/* Note: only src- keys are used in the loop, so the filter narrows the keys to those (their values are always strings) */
const json = themeJson.favicon;
const keys = (Object.keys(json) as (keyof FaviconsJsonType)[]).filter((key): key is Extract<keyof FaviconsJsonType, `src-${string}`> =>
	key.startsWith('src-'),
);
const data: FaviconType[] = [];

/* Not every favicon has head / manifest / purpose / sizes tokens, so those are looked up by string key and may be missing */
const lookup: Record<string, string | boolean | undefined> = json;
const getBoolean = (name: string) => lookup[name] === true;
const getString = (name: string) => {
	const value = lookup[name];
	return typeof value === 'string' ? value : undefined;
};

keys.forEach((favicon) => {
	const current = json[favicon];
	const key = favicon.replace('src-', '');
	const size = getString(`size-${key}`) ?? '';

	// Set type attribute
	let type = 'image/png';
	if (current.includes('.svg')) {
		type = 'image/svg+xml';
	} else if (current.includes('.ico')) {
		type = 'image/x-icon';
	}

	const config: FaviconType = {
		isHead: getBoolean(`head-${key}`),
		isManifest: getBoolean(`manifest-${key}`),
		purpose: getString(`purpose-${key}`) ?? 'any',
		rel: current.includes('apple-touch-icon') ? 'apple-touch-icon' : 'icon',
		src: current,
		size: size,
		sizes: getString(`sizes-${key}`) ?? size,
		type: type,
	};

	data.push(config);
});

export const favicons = data;
