/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by scripts/tokens-generate.js

/* Build font families */
/* Note: only src- keys are used in the loop, so the filter narrows the keys to those (their values are always strings) */
const json = themeJson.font;
const keys = (Object.keys(json) as (keyof FontsJsonType)[]).filter((key): key is Extract<keyof FontsJsonType, `src-${string}`> =>
	key.startsWith('src-'),
);
const data: FontType[] = [];

keys.forEach((font) => {
	const current = json[font];
	const key = font.includes('header') ? 'header' : 'body';
	const weight = font.includes('bold') ? 700 : 400;
	const srcSplit = current.split('.');

	// Preload the non-italic file each family uses first: regular for body text, and the header weight token for headers
	const preloadWeight = key === 'header' ? json['weight-header'] : 400;
	const isPreload = !font.includes('italic') && weight === preloadWeight;

	const config: FontType = {
		display: 'swap',
		ext: srcSplit[srcSplit.length - 1],
		family: json[`name-${key}` as const],
		isPreload: isPreload,
		src: current,
		style: font.includes('italic') ? 'italic' : 'normal',
		weight: weight,
	};

	data.push(config);
});

export const fonts = data;
