/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by scripts/tokens-generate.js

/* Build font families */
/* Note: font tokens are optional, so they're read as a plain map and a project without them gets an empty list */
const json: Record<string, string | number | boolean> = (themeJson as { font?: Record<string, string | number | boolean> }).font ?? {};
const keys = Object.keys(json).filter((key) => key.startsWith('src-'));
const data: FontType[] = [];

/* Get a token as a string (src and name tokens are always strings) */
const getString = (name: string) => {
	const value = json[name];
	return typeof value === 'string' ? value : '';
};

keys.forEach((font) => {
	const current = getString(font).trim();
	const key = font.includes('header') ? 'header' : 'body';
	const weight = font.includes('bold') ? 700 : 400;
	const srcSplit = current.split('.');

	// Fonts can be files or already installed on the device (e.g. local('Courier New'))
	const isLocal = current.startsWith('local(');

	// Preload the non-italic file each family uses first: regular for body text, and the header weight token for headers
	// Note: local fonts aren't downloaded, so they're never preloaded
	const preloadWeight = key === 'header' ? json['weight-header'] : 400;
	const isPreload = !isLocal && !font.includes('italic') && weight === preloadWeight;

	const config: FontType = {
		display: 'swap',
		ext: isLocal ? '' : srcSplit[srcSplit.length - 1],
		family: getString(`name-${key}`),
		isLocal: isLocal,
		isPreload: isPreload,
		src: current,
		style: font.includes('italic') ? 'italic' : 'normal',
		weight: weight,
	};

	data.push(config);
});

export const fonts = data;
