/* Scripts */
import themeJson from '../tokens/theme.json' with { type: 'json' }; // generated by scripts/tokens-generate.js

/* Build project settings */
/* Note: setting tokens are optional, so they're read as a plain map and a project without them gets the defaults (light theme that follows the OS) */
const json: Record<string, string | boolean> = (themeJson as { setting?: Record<string, string | boolean> }).setting ?? {};
const defaultTheme: ThemeModeType = json['theme-default'] === 'dark' ? 'dark' : 'light';

export const settings: SettingsType = {
	theme: {
		default: defaultTheme,
		alternate: defaultTheme === 'dark' ? 'light' : 'dark',
		system: json['theme-system'] !== false,
	},
};
