export const plains: string[] = [
	`Anthologies`,
	`Avacyn Restored`,
	`Battle for Zendikar`,
	`Commander 2013`,
	`Elspeth vs. Kiora`,
	`Duskmourn: House of Horror`,
	`Edge of Eternities`,
	`Fifth Edition`,
	`Final Fantasy`,
	`Ice Age`,
	`Innistrad`,
	`Invasion`,
	`Khans of Tarkir`,
	`Beta`,
	`Lorwyn Eclipsed`,
	`Magic 2012`,
	`Magic 2013`,
	`Magic 2014`,
	`Magic 2015`,
	`Magic Origins`,
	`Mirage`,
	`Mirrodin`,
	`Mirrodin Besieged`,
	`Odyssey`,
	`Portal`,
	`Ravnica: Clue Edition`,
	`Return to Ravnica`,
	`Revised`,
	`Scars of Mirrodin`,
	`Secrets of Strixhaven`,
	`The Hobbit`,
	`Theros`,
	`Unglued`,
	`Unhinged`,
	`Unstable`,
	`Urza's Saga`,
	`War of the Spark`,
	`Zendikar`,
];
