export const mountain: string[] = [
	`Assassin's Creed`,
	`Avacyn Restored`,
	`Battle for Zendikar`,
	`Bloomburrow`,
	`Commander`,
	`Ajani vs. Nicol Bolas`,
	`Venser vs. Koth`,
	`Edge of Eternities`,
	`Final Fantasy`,
	`Guilds of Ravnica`,
	`Ice Age`,
	`Innistrad`,
	`Invasion`,
	`Ixalan`,
	`Jumpstart 2022`,
	`Khans of Tarkir`,
	`Beta`,
	`Lorwyn Eclipsed`,
	`Magic 2011`,
	`Magic 2012`,
	`Magic 2013`,
	`Magic 2014`,
	`Magic 2015`,
	`Mirage`,
	`Mirrodin Besieged`,
	`Odyssey`,
	`Portal`,
	`Fire and Lightning`,
	`Ravnica: Clue Edition`,
	`Return to Ravnica`,
	`Revised`,
	`Rise of the Eldrazi`,
	`Scars of Mirrodin`,
	`Secret Lair Drop Series`,
	`Secrets of Strixhaven`,
	`Seventh Edition`,
	`Shards of Alara`,
	`The Hobbit`,
	`Theros`,
	`Time Spiral`,
	`Unhinged`,
	`Unstable`,
	`War of the Spark`,
	`Zendikar`,
];
