export const swamp: string[] = [
	`Avacyn Restored`,
	`Battle for Zendikar`,
	`Bloomburrow`,
	`Commander`,
	`Commander 2013`,
	`Dragons of Tarkir`,
	`Phyrexia vs. the Coalition`,
	`Edge of Eternities`,
	`Final Fantasy`,
	`Fourth Edition`,
	`Innistrad`,
	`Khans of Tarkir`,
	`Lorwyn Eclipsed`,
	`Magic 2011`,
	`Magic 2012`,
	`Magic 2013`,
	`Magic 2014`,
	`Magic 2015`,
	`Magic Origins`,
	`Mirage`,
	`Mirrodin`,
	`Mirrodin Besieged`,
	`Ninth Edition`,
	`Portal`,
	`Graveborn`,
	`Ravnica: Clue Edition`,
	`Return to Ravnica`,
	`Revised`,
	`Rise of the Eldrazi`,
	`Scars of Mirrodin`,
	`Secrets of Strixhaven`,
	`The Hobbit`,
	`The Lord of the Rings: Tales of Middle-earth`,
	`Theros`,
	`Unfinity`,
	`Unlimited`,
	`Unstable`,
	`Urza's Saga`,
	`War of the Spark`,
	`Zendikar`,
];
